name: weather
description: Weather app CCN Task
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_weather_bg_null_safety:
    git:
      url: https://github.com/nizwar/flutter_weather_background.git
  fluttertoast: ^8.1.2
  geolocator: ^9.0.2
  glass: ^1.0.1+1
  intl: ^0.17.0
  ndialog: ^4.2.1
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sunrise_sunset_calc: ^3.0.0 
  search_map_location: 0.0.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_android.png"
  image_path_ios: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false 
  windows:
    generate: false 
  macos:
    generate: false


flutter:
  uses-material-design: true
  assets:
    - 'assets/'
    - 'assets/images/'
