name: Build Flutter APKs & Appbundle
on: push

jobs:
  build_documentation: 
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'     

      - name: Flutter pub get
        run: flutter pub get

      - name: Install dartdoc
        run: flutter pub global activate dartdoc

      - name: Generate documentation
        run: flutter pub global run dartdoc

      - name: Release the documentation
        uses: crazy-max/ghaction-github-pages@v3
        if: success()
        with:
          target_branch: documentation
          build_dir: doc/api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build APKs
  build_apks:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Initialize project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'     

      - name: Building APKs (Split by ABI)
        run: flutter build apk --release --split-per-abi
 
      - name: Release the APKs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.project_version.outputs.version_number }}-${{github.run_number}}-apks
          name: "Built Apks ${{ steps.project_version.outputs.version_number }} Build(${{github.run_number}})"

  # Build Appbundle
  build_appbundle:
    name: Build APPBUNDLE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Get project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'    

      - name: Building Appbundle
        run: flutter build appbundle

      - name: Release Appbundle
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.project_version.outputs.version_number }}-${{github.run_number}}-appbundle
          name: "Built Appbundle ${{ steps.project_version.outputs.version_number }} Build(${{github.run_number}})"